#!/bin/bash

# Installs node if it isn't already installed
#
# Don't steamroll over a previously installed node version
# TODO provide a local version of node?

VER="@NODE_VERSION"
ARCH="x86"
if [ `arch | grep 64` ]
then
  ARCH="x64"
fi

if [ `arch | grep arm` ]
then
  ARCH="arm-pi"
fi

NODE=`which node`

# TODO test version
if [ ! -n "$NODE" ]
then
  pushd /tmp
  wget -c "http://nodejs.org/dist/v${VER}/node-v${VER}-linux-${ARCH}.tar.gz"
  rm -rf /tmp/node-v${VER}-linux-${ARCH}
  tar xf node-v${VER}-linux-${ARCH}.tar.gz -C /tmp/
  if [ ! -d /opt ] ; then
	mkdir /opt
  fi
  mv /tmp/node-v${VER}-linux-${ARCH} /opt
  ln -s /opt/node-v${VER}-linux-${ARCH} /opt/node
  ln -s /opt/node/bin/node /usr/local/bin/node 
  ln -s /opt/node/bin/npm /usr/local/bin/npm
fi
